library(usethis)

use_package("rrcov", type="Imports")
use_package("fda", type="Imports")
use_package("rlog", type="Imports")
use_package("dplyr", type="Imports")
use_package("ggplot2", type="Imports")
use_package("reshape2", type="Imports")
use_package("mgcv", type="Imports")
use_package("glue", type="Imports")
use_package("tidyr", type="Imports")
use_package("RSpectra", type="Imports")
use_package("kneedle", type="Imports")
use_package("refund", type="Imports")
use_package("robustlmm", type="Imports")
use_package("quantreg", type="Imports")
use_package("MatrixModels", type="Imports")
use_package("Matrix", type="ImYports")
use_package("SparseM", type="Imports")
use_package("quantreg", type="Imports")

use_mit_license()
